var $ZHTW = {
    type: 'zhtw',
    container: {
        my: '我的',
        jackpot: '奖池',
        deadline: '截止时间',
        rang: '让',
        qiu: '球',
        hWin: '主胜',
        ping: '平',
        vWin: '客胜',
        multipl: '倍率',
        singAmount: '单注金额：',
        totalAmount: '总金额：',
        submitBtn: '确定下注',
        isBottomPouring: '正在下注...',
        justWaitResult: '下注成功，请等待最终赛事结果',
        bet: '投注',
        predictAmount: '预计奖金：',
        noWallet: '请创建钱包并登录',
        selectTeams: '请选择下注方',
        balanceNotEnough: '余额不足，请充值',
        deadLineOver: '已过下注截止时间',
        pourBalanceNotEnough: '奖池可用余额不足，下注金额大于奖池可用余额',
        networkError: '网络连接错误，请检查网络！',
    },
    dialog: {
        title: '提示',
        submitBtn: '确定',
    },
    password: {
        title: '请输入密码',
        submitBtn: '确定',
        enterPwd: '请输入密码',
        isUnlocking: '正在解锁...',
        pwdError: '密码不正确',
    },
    record: {
        title: '下注记录',
        timeTitle: '下注时间:',
        hWin: '主胜：',
        ping: '平：',
        vWin: '客胜：',
        singleAmount: '单注金额：',
        totalAmount: '投注总额：',
        rewardAmount: '获奖总额：',
        bei: '倍',
        notWin: '未中奖',
        notOpen: '未开奖',
    },
    appinfo: {
        title: '应用信息',
        info1: '应用名',
        info2: '创建人地址',
        info3: '应用地址',
        info4: '创建时间',
        info5: '奖池余额',
        info6: '下注总金额',
    },
    code: {
        title: '智能合约源码',
    },
    language: {
        title: '语言设置',
    }
};
